name: 'Heroku Deploy'

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "untitled-testing-system"
          heroku_email: "mkogan58@gmail.com"
          dontautocreate: true

          healthcheck: "https://untitled-testing-system.herokuapp.com/health"
          checkstring: "ok"
          delay: 200
          rollbackonhealthcheckfailed: true
