# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Pending status
        uses: ouzi-dev/commit-status-updater@v1.1.2
        with:
          status: "pending"
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Get PR number
        run: PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
      - name: Health check
        uses: jtalk/url-health-check-action@v1.5
        with:
          url: "https://team4-backend-pr-$PR_NUMBER.herokuapp.com/health"
          max-attempts: 10
          retry-delay: 30s
          retry-all: yes
      - name: Status check
        if: always()
        uses: ouzi-dev/commit-status-updater@v1.1.2
        with:
          addHoldComment: "true"
          status: "${{ job.status }}"
